# Netlify configuration for Next.js projects
# https://docs.netlify.com/integrations/frameworks/next-js/

[build]
  # Command to build the project
  command = "npm run build"
  
  # Directory to publish
  publish = ".next"

[[plugins]]
  # The official Netlify plugin for Next.js handles most of the configuration
  package = "@netlify/plugin-nextjs"
