[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/admin"
  to = "/admin/page.html"
  status = 200

[[redirects]]
  from = "/admin/dashboard"
  to = "/admin/dashboard/page.html"
  status = 200
